permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Ajustar nome para index.html
        run: |
         cp ./reports/report.html ./reports/index.html

      - name: Upload artifact (relatório)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./reports

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy no GitHub Pages
        uses: actions/deploy-pages@v4